import {create} from 'zustand';

const authState = create((set, get) => ({
  token: '',
  setToken: token => set({token}),
  Avatar: '',
  setAvatar: Avatar => set({Avatar}),
  refreshToken: '',
  setRefreshToken: refreshToken => set({refreshToken}),
  userProfile: '',
  setuserProfile: userProfile => set({userProfile}),
  loading: false,
  setLoading: loading => set({loading}),
  role: '',
  setRole: role => set({role}),
  listUser: '',
  setlistUser: listUser => set({listUser}),
  editProfile: '',
  setEditProfile: editProfile => set({editProfile}),
  latitudeGPS: '',
  setLatitudeGPS: latitudeGPS => set({latitudeGPS}),
  longitudeGPS: '',
  setLongitudeGPS: longitudeGPS => set({longitudeGPS}),
  saveLoc: '',
  setSaveLoc: saveLoc => set({saveLoc}),
  unSaveLoc: '',
  setUnSaveLoc: unSaveLoc => set({unSaveLoc}),
  cityGPS: '',
  setCityGPS: cityGPS => set({cityGPS}),
  login: '',
  getbyId: '',
  setGetbyId: getbyId => set(getbyId),
  setLogin: login => set({login}),
  getFormbyId: '',
  setgetFormbyID: getFormbyId => set({getFormbyId}),
  setLogout: () =>
    set({
      token: '',
      full_Name: '',
      e_mail: '',
      nick_Name: '',
      Avatar: '',
      refreshToken: '',
      userProfile: '',
      login: '',
      editProfile: '',
      role: '',
      getFormbyId: '',
      listUser: '',
      getbyId: '',
    }),
}));

export default authState;
